services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile # Vue.js 애플리케이션의 디렉토리
    ports:
      - "8080:8080"  # 호스트의 8080 포트를 컨테이너의 8080 포트에 매핑
    networks:
      - labson_network  # custom_network 네트워크 사용
networks:
  labson_network:
    external: true  # 이미 생성된 외부 네트워크를 사용
